name: justdoit
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  sqflite: ^2.3.3+1
  path: ^1.9.0
  uuid: ^4.5.1
  intl: ^0.20.0
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/asuka.png
    - assets/images/rei.png
    - assets/images/shinji.png

